name: cat_facts_randomizer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  retrofit: ^3.0.1+1
  logger: ^1.1.0
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0




dev_dependencies:
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1


  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
